---
# ansible role requirements
- name: vagrant
  src: git+https://github.com/powo-roles/ansible-vagrant.git
  version: master

- name: igloo-ansible-roles
  src: git+https://github.com/igloo-project/igloo-ansible-roles.git
  version: master
