---
# ansible role requirements
- name: vagrant
  src: git+https://github.com/powo-roles/ansible-vagrant.git
  version: master

- name: powo.utils
  src: git+https://github.com/powo-roles/powo.utils.git
  version: master

- name: postgresql
  src: git+https://github.com/igloo-project/roles-postgresql
  version: master

- name: postgresql_cluster
  src: git+https://github.com/igloo-project/roles-postgresql-cluster
  version: master

- name: igloo-ansible-roles
  src: git+https://github.com/igloo-project/igloo-ansible-roles.git
  version: master

- name: letsencrypt
  src: git+https://github.com/igloo-project/ansible-letsencrypt.git
  version: master
