---
# ansible role requirements
- name: vagrant
  src: git+https://github.com/openwide-java/ansible-vagrant.git
  version: master

- name: owsi-core-ansible-roles
  src: git+https://github.com/openwide-java/owsi-core-ansible-roles.git
  version: master
