---
# customizables variables
playbook_application_name: basic-application
playbook_context_name: basic-application
playbook_igloo_profile: qualification
playbook_remote_user: TODO
playbook_maven_environment: null
playbook_project_git_url: TODO
playbook_project_branch: dev
playbook_project_version: 0.1-SNAPSHOT
# choose from centos/7, debian/stretch64
playbook_vagrant_base: centos/7
playbook_application_folders:
  - path: "/data/services/{{ playbook_application_name }}"
    mode: u=rwx,o=rx
    owner: "{{ playbook_remote_user }}"

# provided on command-line (by tasks.py)
# playbook_build_igloo: false
# playbook_build_project: false

# basic-application is in a repository subfolder
# else use root folder
playbook_maven_folder: "{{ 'basic-application/' if playbook_application_name == 'basic-application' else '' }}"
playbook_git_repository_name: "{{ playbook_project_git_url | basename | replace('.git', '') }}"

playbook_igloo_branch: dev
playbook_igloo_version: 1.0-SNAPSHOT

playbook_letsencrypt: no
playbook_letsencrypt_renew_email: "test@example.com"


# customization rarely needed
playbook_download_target_path: /data/work
playbook_is_vagrant_host: "{{ 'vagrant' in group_names }}"
playbook_local_git_repo: ~/git/{{ playbook_git_repository_name }}-livraison
playbook_local_git_repo_path: "{{ playbook_local_git_repo | expanduser }}"
playbook_local_java_home: "{{ '~/Documents/apps/jdk-8' | expanduser }}"
playbook_application_path: /data/services/web/{{ playbook_application_name }}
playbook_application_tomcat_path: "{{ playbook_application_path }}/tomcat"
playbook_ssl_certificate: /etc/httpd/certs/{{ playbook_application_name }}.crt
playbook_ssl_key: /etc/httpd/certs/{{ playbook_application_name }}.key
playbook_ssl_cacertificate: "{{ playbook_ssl_certificate }}"
playbook_httpd_ssl_certificate: "{{ playbook_ssl_certificate }}"
playbook_httpd_ssl_key: "{{ playbook_ssl_key }}"
playbook_httpd_ssl_cacertificate: "{{ playbook_ssl_cacertificate }}"
playbook_local_git_igloo: ~/git/igloo-livraison
playbook_local_git_igloo_path: "{{ playbook_local_git_igloo | expanduser }}"

playbook_front_server_name: "{{ inventory_hostname }}"
playbook_tomcat_ajp_port: 8009
playbook_tomcat_http_port: 8080
playbook_tomcat_shutdown_port: 8005
playbook_tomcat_ajp_max_threads: 15
playbook_tomcat_http_max_threads: 5

playbook_application_name_database: "{{ playbook_application_name | replace('-','_')}}"
playbook_postgresql_port: 5432
playbook_postgresql_host: localhost
playbook_postgresql_database: "{{ playbook_application_name_database }}"
playbook_postgresql_schema: "{{ playbook_postgresql_user }}"
playbook_postgresql_maxPoolSize: 30
playbook_postgresql_user: "{{ playbook_application_name_database }}"
playbook_postgresql_password: "{{ playbook_application_name_database }}"
playbook_smtp_host: smtp.accelance.net
playbook_smtp_port: 25

playbook_config_properties: {
  'db.user': "{{ playbook_postgresql_user }}",
  'db.password': "{{ playbook_postgresql_password }}",
  'db.jdbcUrl': 'jdbc:postgresql://{{ playbook_postgresql_host }}:{{ playbook_postgresql_port }}/{{ playbook_postgresql_database }}',
  'db.maxPoolSize': "{{ playbook_postgresql_maxPoolSize }}",
  'hibernate.defaultSchema': "{{ playbook_postgresql_schema }}",
  'data.path': '{{ playbook_application_path }}/data',
  'data.shared-path': '${data.path}',
  'notification.smtp.host': '{{ playbook_smtp_host }}',
  'notification.smtp.port': "{{ playbook_smtp_port }}",
  'wicket.backgroundThreadContextBuilder.url.serverPort': "{{ playbook_tomcat_http_port }}",
  'task.startMode': 'auto'
}
