---
# ansible role requirements
- name: powo.utils
  src: git+https://github.com/powo-roles/powo.utils.git
  version: main

- name: postgresql
  src: git+https://github.com/igloo-project/roles-postgresql
  version: main

- name: postgresql_cluster
  src: git+https://github.com/igloo-project/roles-postgresql-cluster
  version: main

- name: igloo-ansible-roles
  src: git+https://github.com/igloo-project/igloo-ansible-roles.git
  version: main

- name: letsencrypt
  src: git+https://github.com/igloo-project/ansible-letsencrypt.git
  version: main
