- hosts: owsi-core.vagrant
  gather_facts: no
  roles:
    - role: vagrant
      vagrant_task: 'up'
      vagrant_host: "{{ host_alias | default(inventory_hostname) }}"
      vagrant_root_path: "{{ inventory_dir | dirname }}/vagrant"
      delegate_to: localhost

# this is only an example playbook
# cas server provided by this playbook displays login page
# but is not a fully functionnal running instance.
- hosts: owsi-core.vagrant
  become: yes
  become_user: root
  pre_tasks:
    - name: maven_artifact requisites
      package:
        name: python-lxml
    - name: download cas
      maven_artifact:
        artifact_id: cas-server-webapp
        group_id: org.jasig.cas
        version: 4.2.7
        extension: war
        repository_url: http://repo1.maven.org/maven2
        dest: /tmp/cas.war
  roles:
    - role: utils
    - role: httpd
      httpd_step_install: yes
      httpd_step_configuration: no
    - role: postgresql
      postgresql_versions:
        - "9.5"
    - role: filesystem
      filesystem_application_name: cas
      filesystem_application_user: vagrant
    - role: java
      java_download_path: /data/work
      java_runtime_path: /data/opt
      java_results_var: jdks
      java_runtimes:
        - version: 8u131
          version_build: 11
          arch: x64
          type: jdk
          checksum: md5:75b2cb2249710d822a60f83e28860053
          key: jdk-8u131-x64
          id: d54c1d3a095b4ff2b6607d096fa80163
    - role: ssl_selfsigned
      ssl_selfsigned_cn: cas.dev
      ssl_selfsigned_aliases:
        - cas1.dev
      ssl_selfsigned_certificate: "{{ ssl_certificate }}"
      ssl_selfsigned_key: "{{ ssl_key }}"
    - role: httpd
      httpd_server_name: cas.dev
      httpd_server_aliases:
        - cas1.dev
      httpd_application_name: cas
      httpd_ssl_certificate: "{{ ssl_certificate }}"
      httpd_ssl_key: "{{ ssl_key }}"
    - role: postgresql_cluster
      postgresql_cluster_clusters:
        - name: main
          path: /data/services/postgresql/9.5/data
          postgresql_version: "9.5"
          port: 5432
          databases:
            - name: cas
          users:
            - username: cas
              password: cas
              databases:
                - name: cas
                  privileges: CONNECT,CREATE
    - role: tomcat7
      tomcat7_version: 7.0.73
      tomcat7_checksum: md5:ca9a50ad51d79282f9ca397514c755d7
      tomcat7_dest: /data/opt/tomcat-7.0.73
      tomcat7_default_user: vagrant
      tomcat7_default_java_home: "{{ jdks['jdk-8u131-x64'].path }}"
      tomcat7_catalina_bases:
        - name: cas
          path: /data/services/web/cas/tomcat
    - role: war
      war_application_war_src: /tmp/cas.war
      war_application_war_remote_src: yes
      war_application_war_target: /home/vagrant/cas.war
      war_application_user: vagrant
      war_tomcat_service: tomcat7@cas
      war_tomcat_catalina_base: /data/services/web/cas/tomcat
  vars:
    ssl_certificate: /etc/httpd/certs/application.crt
    ssl_key: /etc/httpd/certs/application.key
